# Generated by Django 6.1.1 on 2026-09-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='tracker_login',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Логин в трекере'),
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('kind', models.CharField(choices=[('login', 'Вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход'), ('role_added', 'Роль выдана'), ('role_removed', 'Роль снята')], max_length=16, verbose_name='Событие')),
                ('username', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('actor', models.CharField(blank=True, default='', max_length=150, verbose_name='Кто изменил')),
                ('detail', models.CharField(blank=True, default='', help_text='Роль — для выдачи и снятия роли', max_length=255, verbose_name='Подробности')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Адрес')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='Браузер')),
            ],
            options={
                'verbose_name': 'событие доступа',
                'verbose_name_plural': 'Журнал доступа',
                'db_table': 'users_access_event',
                'ordering': ('-created', '-id'),
                'indexes': [models.Index(fields=['username', '-created'], name='access_event_user_idx')],
            },
        ),
    ]
