# Generated by Django 6.1.1 on 2026-09-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_fields_access_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tracker_login',
        ),
    ]
