# Generated by Django 6.1.1 on 2026-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_tracker_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='kind',
            field=models.CharField(choices=[('login', 'Вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход'), ('role_added', 'Роль выдана'), ('role_removed', 'Роль снята'), ('user_created', 'Заведён сотрудник')], max_length=16, verbose_name='Событие'),
        ),
    ]
