# Generated by Django 6.1.1 on 2026-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_bom_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomline',
            name='gct_pn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='GCT PN'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='oy_pn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='OY PN'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gct_pn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='GCT PN'),
        ),
        migrations.AlterField(
            model_name='item',
            name='oy_pn',
            field=models.CharField(max_length=255, unique=True, verbose_name='OY PN'),
        ),
    ]
