# Generated by Django 6.1.1 on 2026-09-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_image_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionfield',
            options={'ordering': ('field', 'id'), 'verbose_name': 'выпадающий список', 'verbose_name_plural': 'Выпадающие списки'},
        ),
    ]
