# Generated by Django 6.1.1 on 2026-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_rename_oy_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentchange',
            name='author',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Сотрудник'),
        ),
    ]
