# Generated by Django 6.1.1 on 2026-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_ui_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steprenderjob',
            name='status',
            field=models.CharField(choices=[('queued', 'в очереди'), ('running', 'рисуется'), ('done', 'готова'), ('failed', 'не удалась'), ('superseded', 'заменена новой')], default='queued', max_length=16, verbose_name='Состояние'),
        ),
    ]
