# Generated by Django 6.1.1 on 2026-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_revision_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='gbt_pn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='GBT PN'),
        ),
        migrations.AlterField(
            model_name='boarditem',
            name='oy_pn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='OY PN'),
        ),
        migrations.AlterField(
            model_name='boarditem',
            name='vendor_pn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vendor PN'),
        ),
        migrations.AlterField(
            model_name='boardrevision',
            name='oy_pn',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='OY PN'),
        ),
    ]
