# Generated by Django 6.1.1 on 2026-09-25 12:52

import boards.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_ui_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo_bottom',
            field=models.ImageField(blank=True, upload_to=boards.images.upload_bottom, verbose_name='Изображение — вид снизу'),
        ),
        migrations.AlterField(
            model_name='board',
            name='photo_top',
            field=models.ImageField(blank=True, upload_to=boards.images.upload_top, verbose_name='Изображение — вид сверху'),
        ),
        migrations.AlterField(
            model_name='boardrevision',
            name='photo_bottom',
            field=models.ImageField(blank=True, upload_to=boards.images.revision_bottom, verbose_name='Изображение — вид снизу'),
        ),
        migrations.AlterField(
            model_name='boardrevision',
            name='photo_top',
            field=models.ImageField(blank=True, upload_to=boards.images.revision_top, verbose_name='Изображение — вид сверху'),
        ),
    ]
