-- Таблицы справочника столбцов и их значений.
--
-- Обычно их создаёт `python manage.py migrate`. Этот скрипт нужен, если
-- миграции применять нельзя: например, у пользователя Django нет права
-- CREATE, и схему ведёт администратор базы вручную.
--
-- Запуск:  psql -d components -f sql/create_option_tables.sql
--
-- После этого обязательно отметьте миграции как применённые, иначе Django
-- попробует создать таблицы ещё раз:
--     python manage.py migrate components --fake

CREATE TABLE IF NOT EXISTS oy_option_field (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field     varchar(64)  NOT NULL,
    label     varchar(128) NOT NULL DEFAULT '',
    tables    jsonb        NOT NULL DEFAULT '[]'::jsonb,
    is_active boolean      NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS oy_option_value (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_field_id integer      NOT NULL
                    REFERENCES oy_option_field (id)
                    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    value           varchar(255) NOT NULL,
    is_active       boolean      NOT NULL DEFAULT true,
    CONSTRAINT oy_option_value_field_value_uniq UNIQUE (option_field_id, value)
);

CREATE INDEX IF NOT EXISTS oy_option_value_field_idx
    ON oy_option_value (option_field_id);

-- Пример наполнения; то же самое делает `manage.py load_options --field smt_tht`
-- INSERT INTO oy_option_field (field, label) VALUES ('smt_tht', 'SMT_THT');
-- INSERT INTO oy_option_value (option_field_id, value)
-- SELECT id, v FROM oy_option_field, unnest(ARRAY['SMT', 'THT', '---']) AS v
-- WHERE field = 'smt_tht';
