-- Включает автонумерацию id во всех таблицах справочника.
--
-- Нужен только если колонка id заведена как обычный integer без DEFAULT:
-- тогда вставка новой записи из веб-интерфейса или админки падает с
-- «null value in column "id" violates not-null constraint».
--
-- Скрипт идемпотентный: таблицы, где автонумерация уже есть, пропускаются.
-- Запуск:  psql -d sculptor_db -f sql/enable_id_autoincrement.sql
--
-- Работает по схеме с таблицами компонентов. Если она называется иначе:
--   psql -d sculptor_db -v schema=public -f sql/enable_id_autoincrement.sql

\if :{?schema}
\else
  \set schema public
\endif

SET search_path TO :schema;

DO $$
DECLARE
    t        text;
    has_def  boolean;
    next_id  bigint;
BEGIN
    FOR t IN
        SELECT c.relname
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'r'
          AND n.nspname = current_schema()
          AND EXISTS (
              SELECT 1 FROM information_schema.columns col
              WHERE col.table_schema = n.nspname
                AND col.table_name = c.relname
                AND col.column_name = 'id'
          )
    LOOP
        SELECT a.atthasdef OR a.attidentity <> ''
          INTO has_def
        FROM pg_attribute a
        WHERE a.attrelid = format('%I.%I', current_schema(), t)::regclass
          AND a.attname = 'id';

        IF has_def THEN
            RAISE NOTICE 'таблица % — автонумерация уже есть, пропускаю', t;
            CONTINUE;
        END IF;

        EXECUTE format('SELECT coalesce(max(id), 0) + 1 FROM %I', t) INTO next_id;
        EXECUTE format(
            'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY '
            '(START WITH %s)', t, next_id);
        RAISE NOTICE 'таблица % — автонумерация включена с %', t, next_id;
    END LOOP;
END $$;

-- Первичный ключ (если его нет) заметно ускоряет открытие карточек:
-- ALTER TABLE "CAPACITOR" ADD PRIMARY KEY (id);
